chore: moving to opa-la services and remove opa+envoy from service
MapColonies/pycsw pull request #48
Opened 2023-07-27 13:30 UTC by ronenkapelian

- remove internal auth process via opa+envoy inside nginx pod.
- connecting the nginx making auth with opa-la

2023-07-30 10:02 UTC, alebinson requested changes
Should wait till @AnguIar final solution with code sharing pronciples

2023-07-30 11:02 UTC, asafMasa approved these changes

2023-08-07 09:39 UTC, netanelC requested changes
Please see my review :)

2023-08-07 09:39 UTC, netanelC commented on helm/raster/config/nginx.conf
> +      proxy_pass {{ .Values.rasterCommon.authentication.opa.opaUrl }};
opaUrl field does not exist in values.yaml

2023-08-07 09:39 UTC, netanelC commented on helm/raster/templates/nginx-deployment.yaml
> +          - name: DOMAIN
Could you let me know why you added the domain? in nginx.conf file, you already set the domain variable directly from the values.yaml and not from env.

2023-08-07 09:42 UTC, netanelC commented on helm/raster/templates/nginx-service.yaml
>        # internal
Irrelevant anymore

2024-02-29 15:22 UTC, closed without merging