fix: coordinates formatting in bbox2wktpolygon
MapColonies/pycsw pull request #54
Opened 2023-11-26 21:22 UTC by netanelC

# Overview
Fixes the issue of incorrect formatting of coordinates in the `bbox2wktpolygon` function by updating the coordinate formatting in the return statement.

# Related Issue / Discussion
Closes #53 

# Additional Information
- This change modifies the `bbox2wktpolygon` function in `pycsw/core/util.py` to use `%s` instead of `%.2f` for coordinate formatting.
- Coordinates are now represented as strings without restricting the number of decimal places.

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

2023-11-27 07:34 UTC, asafMasa approved these changes

2023-11-27 08:35 UTC, RonitKissis commented
great job but can it be forwarded by env variable? make it configurable so that the default willl be %.2f if no variable was given?

2023-11-27 08:35 UTC, RonitKissis requested changes
great job but can it be forwarded by env variable? make it configurable so that the default willl be %.2f if no variable was given?

2023-12-03 06:53 UTC, shimoncohen requested changes

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +        A number presenting part of the coordinate
`presenting` -> `representing`.
Even better (IMO):
`A number presenting part of the coordinate` -> `A coordinate single value`

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +        The number with desired formatted precision
`The number with desired formatted precision` -> `The number after formatting`.

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +    num_digits_before_dot = str(abs_number)[::1].find('.')
Default step is 1, why set it explicitly?
And string has [`find`](https://www.w3schools.com/python/ref_string_find.asp) function, why not use it directly?

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +    if(abs_number<1):
Please use spaces in your code when possible for readability.
This is true for other places in this file too.

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +    formatted_number = float(('{:.' + str(int(precision) + num_digits_before_dot) + '}').format(abs_number))
`precision` is already a number, no need for casting.

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +    formatted_number = float(('{:.' + str(int(precision) + num_digits_before_dot) + '}').format(abs_number))
Why aren't you formatting in the form `%.{precision}f`?

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +    num_digits_before_dot = str(abs_number)[::1].find('.')
Why not move this above the `if(str(number).find('.') == -1)` and change the condition?

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +    if(number<0):
Maybe use [ternary operator](https://www.geeksforgeeks.org/ternary-operator-in-python/).

2023-12-03 06:53 UTC, shimoncohen commented on pycsw/core/util.py
> +def format_coord(number):
I think this function can be replaced by `f"{number:.{precision}f}""`. This supports negative values too.

2023-12-03 14:50 UTC, RonitKissis approved these changes

2023-12-03 14:52 UTC, merged