feat: add support to uwsgi exporter (MAPCO-3424)
MapColonies/pycsw pull request #55
Opened 2023-11-29 12:30 UTC by nitzanmorr

# Overview

# Related Issue / Discussion

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

2023-11-29 16:40 UTC, asafMasa requested changes
Great Job!

2023-11-29 16:40 UTC, asafMasa commented on helm/raster/templates/uwsgi-exporter-container.yaml
> +{{- end }}
end of file

2023-11-29 16:40 UTC, asafMasa commented on helm/raster/values.yaml
> +  enabled: true
where is it being used?

2023-11-30 07:44 UTC, CL-SHLOMIKONCHA approved these changes

2023-11-30 08:11 UTC, asafMasa approved these changes

2023-11-30 09:57 UTC, merged