chore: Support OPALA or envoy-opa for authentication (MAPCO-3852)
MapColonies/pycsw pull request #62
Opened 2024-01-29 09:00 UTC by RonitKissis

Support authentication via both Opala and opa-envoy through values configuration

2024-01-29 14:05 UTC, RonitKissis commented on helm/raster/config/log_format.conf
> +            '"connection":"$connection",'
why? this is the same log format that existed in pycsw but i just transfered this code to a separate file

2024-01-30 07:51 UTC, asafMasa commented on helm/raster/config/log_format.conf
> +            '"connection":"$connection",'
please edit like in mapproxy

2024-01-30 13:00 UTC, CL-SHLOMIKONCHA requested changes

2024-01-30 13:00 UTC, CL-SHLOMIKONCHA commented on helm/raster/values.yaml
> +    imagePullSecretName: acr-registry
place an empty string

2024-01-30 13:00 UTC, CL-SHLOMIKONCHA commented on helm/raster/values.yaml
> +  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
place an empty string

2024-01-30 13:00 UTC, CL-SHLOMIKONCHA commented on helm/raster/values.yaml
> +  imagePullSecretName: acr-registry
place an empty string

2024-01-30 15:37 UTC, RonitKissis commented on helm/raster/config/log_format.conf
> +            '"connection":"$connection",'
done

2024-01-30 15:37 UTC, RonitKissis commented on helm/raster/values.yaml
> +    dockerRegistryUrl: acrarolibotnonprod.azurecr.io
done

2024-01-30 15:37 UTC, RonitKissis commented on helm/raster/values.yaml
> +  dockerRegistryUrl: acrarolibotnonprod.azurecr.io
done

2024-01-30 15:52 UTC, asafMasa approved these changes

2024-01-31 08:29 UTC, CL-SHLOMIKONCHA approved these changes

2024-01-31 08:41 UTC, merged