feat: Raster-tile-mime-format (MAPCO-3257)
MapColonies/pycsw pull request #67
Opened 2024-02-19 08:02 UTC by ronenkapelian

* support the tileMimeFormat field.
* raster profile
* tileFormat attribute will retrive from tile_mime_format column on catalog db

2024-02-19 10:31 UTC, asafMasa requested changes

2024-02-19 10:31 UTC, asafMasa commented on pycsw/plugins/profiles/mc_raster/mc_raster.py
> +                        'mc:tileFormat': Queryable(context.md_core_model['mappings']['pycsw:TileFormat'], 'mc:tileFormat'),
change tileFormat to imageFormat

2024-02-19 10:31 UTC, asafMasa commented on helm/raster/config/mappings.py
> +        'pycsw:TileFormat': 'tile_mime_format',
please change 'pycsw:TileFormat' to 'pycsw:ImageFormat'

2024-02-20 07:52 UTC, alebinson approved these changes
just decide about ImageFormat or TileFormat... your call

2024-02-20 15:42 UTC, merged