feat: update raster mapping to new design (MAPCO-4232 , MAPCO-4267)
MapColonies/pycsw pull request #74
Opened 2024-05-15 07:53 UTC by RonitKissis

# Overview

# Related Issue / Discussion

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

2024-05-15 08:05 UTC, netanelC approved these changes
Not related to 3D team

2024-05-15 08:27 UTC, alebinson approved these changes
gr8!

2024-05-15 13:15 UTC, asafMasa requested changes

2024-05-15 13:15 UTC, asafMasa commented on helm/raster/config/mappings.py
> +        'pycsw:minResolutionDeg': 'min_resolution_deg',
please update the following files:
https://github.com/MapColonies/pycsw/blob/762f18cbe0eddef135d384d0c9e844944eb145fd/pycsw/plugins/profiles/mc_raster/mc_raster.py#L40

https://github.com/MapColonies/pycsw/blob/762f18cbe0eddef135d384d0c9e844944eb145fd/pycsw/plugins/profiles/mc_raster/schemas/mcraster-record.xsd#L68

2024-05-16 12:17 UTC, asafMasa approved these changes

2024-05-21 08:57 UTC, merged